main: com.snowmanhunt.snowmanhuntdefault
name: snowmanHunt
version: 1.0
author: Linuxoid86
description: Snowman hunt minigame plugin.
commands:
  seeker:
    description: Sets the seeker.
    usage: /setSeeker *player*
  starthunt:
    description: Starts the game.
    usage: /startHunt
  smhreset:
    description: Resets all minigame effects.
    usage: /smhreset
  smhroundlength:
    description: Sets round duration,
    usage: /smhroundlength *seconds*
  smhstopround:
    description: Stops game
    usage: /smhstopround