main: com.snowmanhunt.snowmanhuntdefault
name: snowmanHunt
version: 1.0
author: Linuxoid86
description: Snowman hunt minigame plugin.
commands:
  seeker:
    description: Sets the seeker.
    usage: /setSeeker *player*
  starthunt:
    description: Starts the game.
    usage: /startHunt